title: Dojune's Blog
author:
  name: Do June Min
  email: dojmin@umich.edu
description: > # this means to ignore newlines until "show_excerpts:"
  My blog

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: 
    github:  
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
    provider: false # false (default), "addtoany", "addthis", "custom"

    ## AddThis
    addthis:
        id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
    provider: disqus # false (default), "disqus", "gitalk", "valine", "custom"

    ## Disqus
    disqus:
        shortname: "https-mindojune-github-io"  # the Disqus shortname for the site

    ## Gitalk
    # please refer to https://github.com/gitalk/gitalk for more info.
    gitalk:
        clientID    : 'd27853a53940af0d253f' # GitHub Application Client ID
        clientSecret: 'a2e22832e24bfefb1702b8dc1150b101f25e81b2' # GitHub Application Client Secret
        repository  : 'mindojune.github.io' # GitHub repo
        owner       : 'mindojune' # GitHub repo owner
        admin: ['mindojune'] # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
            # - your GitHub Id

    ## Valine
    # please refer to https://valine.js.org/en/ for more info.
    valine:
        app_id      : # LeanCloud App id
        app_key     : # LeanCloud App key
        placeholder : # Prompt information
        visitor     : # false (default)
        meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
    provider: false # false (default), "leancloud", "custom"

    ## Leancloud
    leancloud:
        app_id    : # LeanCloud App id
        app_key   : # LeanCloud App key
        app_class : # LeanCloud App class


## => Search
##############################
search:
    provider: default # "default" (default), false, "google", "custom"

    ## Google Custom Search Engine
    google:
        custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
    provider: google  # false (default), "google", "custom"

    ## Google Analytics
    google:
        tracking_id : UA-121680114-1 # Google Analytics id for the site
        anonymize_ip: true  # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
    - CHANGELOG.md
    - HOW_TO_RELEASE.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README-*.md
    - README.md
    - gulpfile.js
    - jekyll-text-theme.gemspec
    - package-lock.json
    - package.json
    - /docs
    - /node_modules
    - /screenshots
    - /test
    - /vendor

defaults:
    - scope:
            path: ""
            type: posts
        values:
            layout: article
            sharing: true
            license: true
            aside:
                toc: true
            show_edit_on_github: true
            show_subscribe: true
            pageview: true


## => Plugins
##############################
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
    - jemoji
