# Improved _config.yml for your Jekyll Blog

# General Site Settings
minimal_mistakes_skin    : "air"  # Changed to a more visually appealing skin
title                    : "Do June Min - Technology, Research, and Insights"
description              : "PhD Student exploring technology, data science, and research with a focus on innovation."
locale                   : "en-US"
url                      : "https://mindojune.github.io"
baseurl                  : ""
repository               : "mindojune/mindojune.github.io"
teaser                   : "default_teaser.jpg"  # Add a teaser image to make the homepage more engaging
breadcrumbs              : true  # Enable breadcrumbs for better navigation
words_per_minute         : 160
future                   : true
read_more                : "enabled"  # Enable "Read more" links to make longer posts easier to explore

# Author and Social Media Settings
name                     : &name "Do June Min"
author_profile           : true
social:
  - title: "GitHub"
    url: "https://github.com/your_username"
  - title: "Twitter"
    url: "https://twitter.com/your_username"

# Comments Configuration
comments:
  provider               : "disqus"
  disqus:
    shortname            : "https-mindojune-github-io"

# Collections and Layout Customization
collections:
  home:
    output: true
    permalink: "/"
  posts:
    output: true
    permalink: /:categories/:title/
    layout: single
    author_profile: true
    share: true
    comments: true

# Sass/SCSS Customizations
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
